
# Mapping of Cyrillic to Latin alphabet
cyrillic_transliteration = {
    u'А': u'A', u'а': u'a',
    u'Б': u'B', u'б': u'b',
    u'В': u'V', u'в': u'v',
    u'Г': u'G', u'г': u'g',
    u'Д': u'D', u'д': u'd',
    u'Ђ': u'Đ', u'ђ': u'đ',
    u'Е': u'E', u'е': u'e',
    u'Ж': u'Ž', u'ж': u'ž',
    u'З': u'Z', u'з': u'z',
    u'И': u'I', u'и': u'i',
    u'Ј': u'J', u'ј': u'j',
    u'К': u'K', u'к': u'k',
    u'Л': u'L', u'л': u'l',
    u'Љ': u'Lj', u'љ': u'lj',
    u'М': u'M', u'м': u'm',
    u'Н': u'N', u'н': u'n',
    u'Њ': u'Nj', u'њ': u'nj',
    u'О': u'O', u'о': u'o',
    u'П': u'P', u'п': u'p',
    u'Р': u'R', u'р': u'r',
    u'С': u'S', u'с': u's',
    u'Т': u'T', u'т': u't',
    u'Ћ': u'Ć', u'ћ': u'ć',
    u'У': u'U', u'у': u'u',
    u'Ф': u'F', u'ф': u'f',
    u'Х': u'H', u'х': u'h',
    u'Ц': u'C', u'ц': u'c',
    u'Ч': u'Č', u'ч': u'č',
    u'Џ': u'Dž', u'џ': u'dž',
    u'Ш': u'Š', u'ш': u'š',
    u' ': u' ', u'%': u'%'
}

# Supported languages that 'MilanBot' works with
languages = {
    'afrikans': 'af',
    'arabic': 'ar',
    'armenian': 'hy',
    'belorussian': 'be',
    'belorussian-taraskievica': 'be-tarask',
    'bosnian': 'bs',
    'bulgarian': 'bg',
    'catalan': 'ca',
    'cantonese': 'yue',
    'chinese': 'zh',
    'chinese-classical': 'lzh',
    'chinese-hakka': 'hak',
    'chinese-min-nan': 'nan',
    'chinese-cn': 'zh-cn',
    'chinese-hans': 'zh-hans',
    'chinese-hant': 'zh-hant',
    'chinese-hongkong': 'zh-hk',
    'chinese-mo': 'zh-mo',
    # 'chinese-my': 'zh-my',
    'chinese-singapore': 'zh-sg',
    'chinese-taiwanese': 'zh-tw',
    'czech': 'cs',
    'croatian': 'hr',
    'dutch': 'nl',
    'dutch-low-saxon': 'nds-nl',
    'english': 'en',
    'english-british': 'en-gb',
    'english-canadian': 'en-ca',
    'estonian': 'et',
    'esperanto': 'eo',
    'frisian-west': 'fy',
    'frisian-north': 'frr',
    'french': 'fr',
    'finish': 'fi',
    'galician': 'gl',
    'german': 'de',
    'german-austrian': 'de-at',
    'german-swiss': 'de-ch',
    'georgian': 'ka',
    'greek': 'el',
    'italian': 'it',
    'japanese': 'ja',
    'kannada': 'kn',
    'khmer': 'km',
    'korean': 'ko',
    'latvian': 'lv',
    'macedonian': 'mk',
    'malayalam': 'ml',
    'mazandarani': 'mzn',
    'norwegian-nynorsk': 'nn',
    'occitan': 'oc',
    'odia': 'or',
    'pashto': 'ps',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'portuguese-brazilian': 'pt-br',
    'ripuarian': 'ksh',
    'romanian': 'ro',
    'russian': 'ru',
    'sorani': 'ckb',
    'scots': 'sco',
    'serbian': 'sr',
    'sr-cyrillic': 'sr-ec',
    'sr-latin': 'sr-el',
    'serbocroatian': 'sh',
    'sicilian': 'scn',
    'spanish': 'es',
    'swedish': 'sv',
    'tamil': 'ta',
    'thai': 'th',
    'turkish': 'tr',
    'ukrainian': 'uk',
    'vietnamese': 'vi',
    'welsh': 'cy',
}